"""Added foreign key

Revision ID: 37495ca745d8
Revises: bb3e3c9ad801
Create Date: 2022-09-18 14:28:02.544675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37495ca745d8'
down_revision = 'bb3e3c9ad801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('poster_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['poster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'poster_id')
    # ### end Alembic commands ###
